### ISSUE TITLE
Missing "peerDependencies"

### ISSUE THREAD

**Issue by hmozaffari** [jqassistant-plugin/jqassistant-npm-plugin#9]
In addition to "dependencies" and "devDependencies" npm offers "[peerDependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies)". It would be great if that type of dependency also get covered by model:

https://github.com/jqassistant-plugin/jqassistant-npm-plugin/blob/6ebefa7825915e0180bc3fa81166fe550bd592e8/src/main/java/org/jqassistant/plugin/npm/api/model/PackageDescriptor.java#L58

**Comment by SebastianWendorf** [comment]
Fixed with #10
